document.addEventListener('DOMContentLoaded', function () {

	$('#test').slider({
		items: [
			{
				src: 'img/1.jpg',
				title: 'Test1',
				sort: 3
			},
			{
				src: 'img/2.jpg',
				title: 'Test2',
				sort: 2
			},
			{
				src: 'img/3.jpg',
				title: 'Test3',
				sort: 3
			},
			{
				src: 'img/4.jpg',
				title: 'Test4',
				sort: 6
			},
			{
				src: 'img/5.jpg',
				title: 'Test5',
				sort: 10
			},
			{
				src: 'img/6.jpg',
				title: 'Test6',
				sort: 1
			},
			{
				src: 'img/7.jpg',
				title: {
					'ua': 'Тест 7',
					'en': 'Test 7'
				},
				sort: 7,
				description: {
					'ua': 'аллала',
					'en': 'lalallala'
				}
			},
			{
				src: 'img/8.jpg',
				title: 'Test8',
				sort: 8,
				description: 'Будь-яке виробництво складається з Технологічних процесів, які уявляють собою дерево та утворюють основні процеси, які присутні на підприємстві. Завдяки опису саме їх отримуємо загальну уяву про виробництво продукції, яке починається з видачі сировини у виробництво та її перетворення у напівфабрикати на різних дільницях.'

			},
			{
				src: 'img/9.jpg',
				sort: 0,
				description: {
					'ua': 'Будь-яке виробництво складається з Технологічних процесів, які уявляють собою дерево та утворюють основні процеси, які присутні на підприємстві. Завдяки опису саме їх отримуємо загальну уяву про виробництво продукції, яке починається з видачі сировини у виробництво та її перетворення у напівфабрикати на різних дільницях.',
					'en': 'test'
				}

			},
			{
				src: '',
				title: 'Test10',
				sort: 1
			},
		],
		playState: 0,
		playDelay: 1000,
		beforeOpen: (options) => {
			options.dataSource.lang = 'ua';
		}
	})

	$('#test2').slider({
		items: [
			{
				src: 'img/1.jpg',
				title: 'Test1'
			},
			{
				src: 'img/2.jpg',
				title: 'Test2'
			},
			{
				src: 'img/3.jpg',
				title: 'Test3'
			},
			{
				src: 'img/4.jpg',
				title: 'Test4'
			},
			{
				src: 'img/5.jpg',
				title: 'Test5'
			},
			{
				src: 'img/6.jpg',
				title: 'Test6'
			},
			{
				src: 'img/7.jpg',
				title: 'Test7'
			},
		]
	})

	$('#testInput1').klevisInput({
		
		label: {
			'ru': 'Первый инпут',
			'ua': 'Перший інпут',
			'en': 'First input'
		},
		type: 'password',
		lang: 'ru',

		beforeOpen: (options) => {
		},
		
		validOptions: (options) => {

			if (!options.val){
		
				options.required = true;
				options.validText = {
					'ru': 'Обязательное поле',
					'ua': 'Обов’язкове поле',
					'en': 'Required field'
				};

			} else if (options.val.length < 5){
		
				options.required = true;
				options.validText = 'you must have at least 5 characters'
				
			} else {
				options.required = false;
			}
		}

	})

	$('#testInput2').klevisInput({
		
		label: {
			'ru': 'Второй инпут',
			'eng': 'Second input'
		},
		value: 123,
		beforeOpen: (options) => {
		},
		
		validText: {
			'ru': 'Обов’язкове поле',
			'eng': 'Required field'
		},
		lang: 'eng',
		
		validOptions: (options) => {
			if (!options.val){
				options.required = true;
			} else {
				options.required = false;
			}
		}

	})

	
	$('#testInput3').klevisInput({
		label: 'test input 4',
		displayImageControl: false
	})

	$('#testInput4').klevisInput({
		imageControl: `/img/2.jpg`,
		change: (options) => {
			console.log(options.val)
		},
	})

	
	$('#testInput5').klevisInput({
		changeImageControl: true
	})


	//https://myjson.com
	$('.testSelectList1').klevisSelectList({
		label: 'Select 1',
		textField: 'name',
		valueField: 'abbreviation',
		nullOption: true,
		autoRead: false,
		filter: true,
		validOptions: (options) => {
			//console.log(options.value);
			if (!options.value){
				options.required = true;
				options.validText = {
					'ru': 'Обов’язкове поле',
					'eng': 'Required field'
				};
			} else {
				options.required = false;
			}
		},
		//textField: 'text',
		//valueField: 'value',
		source: {
			// items : [{
			// 	text: 'test1',
			// 	value: 1
			// }, {
			// 	text: 'test2',
			// 	value: 2
			// }, {
			// 	text: 'test3',
			// 	value: 3
			// }]
			
			transport(options){
				$.ajax({
					type: "GET",
					url: "https://api.myjson.com/bins/bnx96",
					//url: "https://api.myjson.com/bins/104u7u",
					success: (data) => {
						options.success(data);
					}
				});
			}
		},
		change(options){
			$('#testInput5').data('klevisInput').val = options.value
			//console.log(options.value);
		}

	})

	
	$('.testSelectList2').klevisSelectList({
		label: 'Select 2',
		textField: 'name',
		valueField: 'abbreviation',
		filter: true,
		displayImageControl: false,
		source: {
			items : [{
				name: "test323",
				abbreviation: '1'
			}, {
				name: 'test123',
				abbreviation: '2'
			}, {
				name: 'test45',
				abbreviation: '3'
			}]
		},

	})

	
	$('.testSelectList3').klevisSelectList({
		label: 'Select Manufactures MySql',
		textField: 'description',
		valueField: 'id',
		filter: true,
		nullOption: true,
		autoRead: false,
		source: {
			transport(options){
				$.ajax({
					type: "GET",
					url: "https://api.myjson.com/bins/xmrxw",
					success: (data) => {
						options.success(data);
					}
				});
			}
		}
	})

	/*$('.testMultiSelectList1').klevisMultiSelectList({
		label: 'Multi Select 1',
		textField: 'name',
		valueField: 'abbreviation',
		filter: true,
		displayImageControl: false,
		source: {
			items : [{
				name: 'TEST323',
				abbreviation: '1'
			}, {
				name: 'TEST123',
				abbreviation: '2'
			}, {
				name: 'TEST45',
				abbreviation: '3'
			}]
		},

	})*/

	$('.testListView').klevisListView({
		label: 'Manufacturers',
		textField: 'description',
		valueField: 'id',
		groupField: 'firstlatter',
		numColls: 3,
		filter: true,
		height: 500,
		change: (options) => {
			console.log(options.dataItem)
		},
		source: {
			
			transport(options){
				$.ajax({
					type: "GET",
					url: "https://api.myjson.com/bins/1bj556",
					success: (data) => {
						//console.log(data)
						options.success(data);
					}
				});
			}

		},
		
		/*textField: 'name',
		valueField: 'abbreviation',
		groupField: 'group',
		numColls: 1,
		filter: true,
		//height: 100,
		source: {
			items : [{
				name: "test323",
				abbreviation: '1',
				group: 'a'
			}, {
				name: 'test123',
				abbreviation: '2',
				group: 'a'
			}, {
				name: 'test45',
				abbreviation: '3',
				group: 'b'
			}, {
				name: 'test5',
				abbreviation: '3',
				group: 'c'
			}, {
				name: 'test457',
				abbreviation: '3',
				group: 'd'
			}, {
				name: 'test453',
				abbreviation: '3',
				group: 's'
			}]
		},*/
		/*source: {
			items : [
			{
			"id":2
			,"canbedisplayed":true
			,"description":"ALFA ROMEO"
			,"fulldescription":"ALFA ROMEO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ALFA"
			,"firstlatter":"A"
			}
			,{
			"id":3854
			,"canbedisplayed":true
			,"description":"ABARTH"
			,"fulldescription":"ABARTH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ABARTH"
			,"firstlatter":"A"
			}
			,{
			"id":5
			,"canbedisplayed":true
			,"description":"AUDI"
			,"fulldescription":"AUDI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AUDI"
			,"firstlatter":"A"
			}
			,{
			"id":6
			,"canbedisplayed":true
			,"description":"AUSTIN"
			,"fulldescription":"AUSTIN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AUSTI"
			,"firstlatter":"A"
			}
			,{
			"id":132
			,"canbedisplayed":true
			,"description":"AVIA"
			,"fulldescription":"AVIA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AVIA"
			,"firstlatter":"A"
			}
			,{
			"id":609
			,"canbedisplayed":true
			,"description":"AC"
			,"fulldescription":"AC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AC"
			,"firstlatter":"A"
			}
			,{
			"id":799
			,"canbedisplayed":true
			,"description":"AUTOBIANCHI"
			,"fulldescription":"AUTOBIANCHI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AUTOB"
			,"firstlatter":"A"
			}
			,{
			"id":810
			,"canbedisplayed":true
			,"description":"ALPINE"
			,"fulldescription":"ALPINE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ALPIN"
			,"firstlatter":"A"
			}
			,{
			"id":866
			,"canbedisplayed":true
			,"description":"ALPINA"
			,"fulldescription":"ALPINA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ALPI"
			,"firstlatter":"A"
			}
			,{
			"id":879
			,"canbedisplayed":true
			,"description":"ASIA MOTORS"
			,"fulldescription":"ASIA MOTORS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ASIAM"
			,"firstlatter":"A"
			}
			,{
			"id":881
			,"canbedisplayed":true
			,"description":"ASTON MARTIN"
			,"fulldescription":"ASTON MARTIN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ASTON"
			,"firstlatter":"A"
			}
			,{
			"id":1360
			,"canbedisplayed":true
			,"description":"ARO"
			,"fulldescription":"ARO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ARO"
			,"firstlatter":"A"
			}
			,{
			"id":1480
			,"canbedisplayed":true
			,"description":"AIXAM"
			,"fulldescription":"AIXAM"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AIXAM"
			,"firstlatter":"A"
			}
			,{
			"id":1505
			,"canbedisplayed":true
			,"description":"ACURA"
			,"fulldescription":"ACURA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ACURA"
			,"firstlatter":"A"
			}
			,{
			"id":1538
			,"canbedisplayed":true
			,"description":"AUSTIN-HEALEY"
			,"fulldescription":"AUSTIN-HEALEY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AUSTIN-HEA"
			,"firstlatter":"A"
			}
			,{
			"id":2241
			,"canbedisplayed":true
			,"description":"ASHOK LEYLAND"
			,"fulldescription":"ASHOK LEYLAND"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ASHOK LEYL"
			,"firstlatter":"A"
			}
			,{
			"id":2242
			,"canbedisplayed":true
			,"description":"ASKAM (FARGO\/DESOTO)"
			,"fulldescription":"ASKAM (FARGO\/DESOTO)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ASKAM"
			,"firstlatter":"A"
			}
			,{
			"id":2246
			,"canbedisplayed":true
			,"description":"AMC"
			,"fulldescription":"AMC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AMC"
			,"firstlatter":"A"
			}
			,{
			"id":3495
			,"canbedisplayed":true
			,"description":"ARTEGA"
			,"fulldescription":"ARTEGA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ARTEGA"
			,"firstlatter":"A"
			}
			,{
			"id":3
			,"canbedisplayed":true
			,"description":"AUTO UNION"
			,"fulldescription":"AUTO UNION"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"AUTOU"
			,"firstlatter":"A"
			}
			,{
			"id":10
			,"canbedisplayed":true
			,"description":"BEDFORD"
			,"fulldescription":"BEDFORD"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BEDFO"
			,"firstlatter":"B"
			}
			,{
			"id":16
			,"canbedisplayed":true
			,"description":"BMW"
			,"fulldescription":"BMW"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BMW"
			,"firstlatter":"B"
			}
			,{
			"id":134
			,"canbedisplayed":true
			,"description":"BARKAS"
			,"fulldescription":"BARKAS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BARKA"
			,"firstlatter":"B"
			}
			,{
			"id":136
			,"canbedisplayed":true
			,"description":"BORGWARD"
			,"fulldescription":"BORGWARD"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BORGW"
			,"firstlatter":"B"
			}
			,{
			"id":788
			,"canbedisplayed":true
			,"description":"BUGATTI"
			,"fulldescription":"BUGATTI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BUGAT"
			,"firstlatter":"B"
			}
			,{
			"id":815
			,"canbedisplayed":true
			,"description":"BENTLEY"
			,"fulldescription":"BENTLEY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BENT"
			,"firstlatter":"B"
			}
			,{
			"id":816
			,"canbedisplayed":true
			,"description":"BUICK"
			,"fulldescription":"BUICK"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BUICK"
			,"firstlatter":"B"
			}
			,{
			"id":1485
			,"canbedisplayed":true
			,"description":"BERTONE"
			,"fulldescription":"BERTONE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BERT"
			,"firstlatter":"B"
			}
			,{
			"id":1486
			,"canbedisplayed":true
			,"description":"BITTER"
			,"fulldescription":"BITTER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BITTER"
			,"firstlatter":"B"
			}
			,{
			"id":1487
			,"canbedisplayed":true
			,"description":"BRISTOL"
			,"fulldescription":"BRISTOL"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BRIST"
			,"firstlatter":"B"
			}
			,{
			"id":1537
			,"canbedisplayed":true
			,"description":"BOND"
			,"fulldescription":"BOND"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BOND"
			,"firstlatter":"B"
			}
			,{
			"id":3071
			,"canbedisplayed":true
			,"description":"BAW"
			,"fulldescription":"BAW"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BAW"
			,"firstlatter":"B"
			}
			,{
			"id":3076
			,"canbedisplayed":true
			,"description":"BRILLIANCE"
			,"fulldescription":"BRILLIANCE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BRILLIANCE"
			,"firstlatter":"B"
			}
			,{
			"id":3122
			,"canbedisplayed":true
			,"description":"BYD"
			,"fulldescription":"BYD"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BYD"
			,"firstlatter":"B"
			}
			,{
			"id":3762
			,"canbedisplayed":true
			,"description":"BESTURN (FAW)"
			,"fulldescription":"BESTURN (FAW)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BESTURN"
			,"firstlatter":"B"
			}
			,{
			"id":4439
			,"canbedisplayed":true
			,"description":"BOGDAN"
			,"fulldescription":"BOGDAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"BOGDAN"
			,"firstlatter":"B"
			}
			,{
			"id":20
			,"canbedisplayed":true
			,"description":"CHRYSLER"
			,"fulldescription":"CHRYSLER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CHRYS"
			,"firstlatter":"C"
			}
			,{
			"id":21
			,"canbedisplayed":true
			,"description":"CITROEN"
			,"fulldescription":"CITROEN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CITRO"
			,"firstlatter":"C"
			}
			,{
			"id":138
			,"canbedisplayed":true
			,"description":"CHEVROLET"
			,"fulldescription":"CHEVROLET"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CHEVR"
			,"firstlatter":"C"
			}
			,{
			"id":819
			,"canbedisplayed":true
			,"description":"CADILLAC"
			,"fulldescription":"CADILLAC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CADIL"
			,"firstlatter":"C"
			}
			,{
			"id":1488
			,"canbedisplayed":true
			,"description":"CALLAWAY"
			,"fulldescription":"CALLAWAY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CALLA"
			,"firstlatter":"C"
			}
			,{
			"id":3772
			,"canbedisplayed":true
			,"description":"CMC"
			,"fulldescription":"CMC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CMC"
			,"firstlatter":"C"
			}
			,{
			"id":1490
			,"canbedisplayed":true
			,"description":"CATERHAM"
			,"fulldescription":"CATERHAM"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CATE"
			,"firstlatter":"C"
			}
			,{
			"id":1491
			,"canbedisplayed":true
			,"description":"CHECKER"
			,"fulldescription":"CHECKER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CHECK"
			,"firstlatter":"C"
			}
			,{
			"id":2852
			,"canbedisplayed":true
			,"description":"CHANGAN"
			,"fulldescription":"CHANGAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CHANGAN"
			,"firstlatter":"C"
			}
			,{
			"id":2887
			,"canbedisplayed":true
			,"description":"CHERY"
			,"fulldescription":"CHERY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CHERY"
			,"firstlatter":"C"
			}
			,{
			"id":2889
			,"canbedisplayed":true
			,"description":"CHANGFENG"
			,"fulldescription":"CHANGFENG"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CHANGFENG"
			,"firstlatter":"C"
			}
			,{
			"id":1489
			,"canbedisplayed":true
			,"description":"CARBODIES"
			,"fulldescription":"CARBODIES"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"CARBO"
			,"firstlatter":"C"
			}
			,{
			"id":24
			,"canbedisplayed":true
			,"description":"DAF"
			,"fulldescription":"DAF"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DAF"
			,"firstlatter":"D"
			}
			,{
			"id":25
			,"canbedisplayed":true
			,"description":"DAIHATSU"
			,"fulldescription":"DAIHATSU"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DAIHA"
			,"firstlatter":"D"
			}
			,{
			"id":26
			,"canbedisplayed":true
			,"description":"DAIMLER"
			,"fulldescription":"DAIMLER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DAIML"
			,"firstlatter":"D"
			}
			,{
			"id":29
			,"canbedisplayed":true
			,"description":"DODGE"
			,"fulldescription":"DODGE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DODGE"
			,"firstlatter":"D"
			}
			,{
			"id":139
			,"canbedisplayed":true
			,"description":"DACIA"
			,"fulldescription":"DACIA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DACIA"
			,"firstlatter":"D"
			}
			,{
			"id":185
			,"canbedisplayed":true
			,"description":"DAEWOO"
			,"fulldescription":"DAEWOO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DAEWOO"
			,"firstlatter":"D"
			}
			,{
			"id":4468
			,"canbedisplayed":true
			,"description":"DS"
			,"fulldescription":"DS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DS"
			,"firstlatter":"D"
			}
			,{
			"id":1493
			,"canbedisplayed":true
			,"description":"DALLAS"
			,"fulldescription":"DALLAS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DALLA"
			,"firstlatter":"D"
			}
			,{
			"id":1494
			,"canbedisplayed":true
			,"description":"DE LOREAN"
			,"fulldescription":"DE LOREAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DELOR"
			,"firstlatter":"D"
			}
			,{
			"id":1495
			,"canbedisplayed":true
			,"description":"DE TOMASO"
			,"fulldescription":"DE TOMASO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DETOM"
			,"firstlatter":"D"
			}
			,{
			"id":2854
			,"canbedisplayed":true
			,"description":"DONGFENG (DFAC)"
			,"fulldescription":"DONGFENG (DFAC)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DFAC"
			,"firstlatter":"D"
			}
			,{
			"id":3069
			,"canbedisplayed":true
			,"description":"DERWAYS"
			,"fulldescription":"DERWAYS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DERWAYS"
			,"firstlatter":"D"
			}
			,{
			"id":807
			,"canbedisplayed":true
			,"description":"DATSUN"
			,"fulldescription":"DATSUN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"DATSUN"
			,"firstlatter":"D"
			}
			,{
			"id":142
			,"canbedisplayed":true
			,"description":"EBRO"
			,"fulldescription":"EBRO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"EBRO"
			,"firstlatter":"E"
			}
			,{
			"id":3704
			,"canbedisplayed":true
			,"description":"ENGLON (GEELY)"
			,"fulldescription":"ENGLON (GEELY)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ENGLON"
			,"firstlatter":"E"
			}
			,{
			"id":3332
			,"canbedisplayed":true
			,"description":"EMGRAND (GEELY)"
			,"fulldescription":"EMGRAND (GEELY)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"EMGRAND"
			,"firstlatter":"E"
			}
			,{
			"id":35
			,"canbedisplayed":true
			,"description":"FIAT"
			,"fulldescription":"FIAT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FIAT"
			,"firstlatter":"F"
			}
			,{
			"id":36
			,"canbedisplayed":true
			,"description":"FORD"
			,"fulldescription":"FORD"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FORD"
			,"firstlatter":"F"
			}
			,{
			"id":700
			,"canbedisplayed":true
			,"description":"FERRARI"
			,"fulldescription":"FERRARI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FERRA"
			,"firstlatter":"F"
			}
			,{
			"id":775
			,"canbedisplayed":true
			,"description":"FSO"
			,"fulldescription":"FSO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FSO"
			,"firstlatter":"F"
			}
			,{
			"id":3738
			,"canbedisplayed":true
			,"description":"FISKER"
			,"fulldescription":"FISKER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FISKER"
			,"firstlatter":"F"
			}
			,{
			"id":808
			,"canbedisplayed":true
			,"description":"FORD OTOSAN"
			,"fulldescription":"FORD OTOSAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FORDOTOSAN"
			,"firstlatter":"F"
			}
			,{
			"id":2867
			,"canbedisplayed":true
			,"description":"FOTON"
			,"fulldescription":"FOTON"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FOTON"
			,"firstlatter":"F"
			}
			,{
			"id":2890
			,"canbedisplayed":true
			,"description":"FAW TIANJIN"
			,"fulldescription":"FAW TIANJIN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FAW TJ"
			,"firstlatter":"F"
			}
			,{
			"id":776
			,"canbedisplayed":true
			,"description":"FORD USA"
			,"fulldescription":"FORD USA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"FORD USA"
			,"firstlatter":"F"
			}
			,{
			"id":39
			,"canbedisplayed":true
			,"description":"GMC"
			,"fulldescription":"GMC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GMC"
			,"firstlatter":"G"
			}
			,{
			"id":148
			,"canbedisplayed":true
			,"description":"GAZ"
			,"fulldescription":"GAZ"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GAZ"
			,"firstlatter":"G"
			}
			,{
			"id":812
			,"canbedisplayed":true
			,"description":"GLAS"
			,"fulldescription":"GLAS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GLAS"
			,"firstlatter":"G"
			}
			,{
			"id":3997
			,"canbedisplayed":true
			,"description":"GAC GONOW"
			,"fulldescription":"GAC GONOW"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GACGONOW"
			,"firstlatter":"G"
			}
			,{
			"id":1498
			,"canbedisplayed":true
			,"description":"GINETTA"
			,"fulldescription":"GINETTA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GINET"
			,"firstlatter":"G"
			}
			,{
			"id":2590
			,"canbedisplayed":true
			,"description":"GEELY"
			,"fulldescription":"GEELY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GEELY"
			,"firstlatter":"G"
			}
			,{
			"id":2903
			,"canbedisplayed":true
			,"description":"GREAT WALL"
			,"fulldescription":"GREAT WALL"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GREAT WALL"
			,"firstlatter":"G"
			}
			,{
			"id":831
			,"canbedisplayed":true
			,"description":"GEO"
			,"fulldescription":"GEO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"GEO"
			,"firstlatter":"G"
			}
			,{
			"id":45
			,"canbedisplayed":true
			,"description":"HONDA"
			,"fulldescription":"HONDA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HONDA"
			,"firstlatter":"H"
			}
			,{
			"id":183
			,"canbedisplayed":true
			,"description":"HYUNDAI"
			,"fulldescription":"HYUNDAI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HYUNDAI"
			,"firstlatter":"H"
			}
			,{
			"id":1499
			,"canbedisplayed":true
			,"description":"HINDUSTAN"
			,"fulldescription":"HINDUSTAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HINDU"
			,"firstlatter":"H"
			}
			,{
			"id":1500
			,"canbedisplayed":true
			,"description":"HOBBYCAR"
			,"fulldescription":"HOBBYCAR"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HOBBY"
			,"firstlatter":"H"
			}
			,{
			"id":4258
			,"canbedisplayed":true
			,"description":"HUANGHAI"
			,"fulldescription":"HUANGHAI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HUANGHAI"
			,"firstlatter":"H"
			}
			,{
			"id":2866
			,"canbedisplayed":true
			,"description":"HAFEI"
			,"fulldescription":"HAFEI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HAFEI"
			,"firstlatter":"H"
			}
			,{
			"id":3036
			,"canbedisplayed":true
			,"description":"HAIMA (FAW)"
			,"fulldescription":"HAIMA (FAW)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HAIMA(FAW)"
			,"firstlatter":"H"
			}
			,{
			"id":3129
			,"canbedisplayed":true
			,"description":"HONDA (GAC)"
			,"fulldescription":"HONDA (GAC)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HONDA GAC"
			,"firstlatter":"H"
			}
			,{
			"id":3913
			,"canbedisplayed":true
			,"description":"HAIMA (ZHENGZHOU)"
			,"fulldescription":"HAIMA (ZHENGZHOU)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HAIMA(ZZ)"
			,"firstlatter":"H"
			}
			,{
			"id":1506
			,"canbedisplayed":true
			,"description":"HUMMER"
			,"fulldescription":"HUMMER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"HUMME"
			,"firstlatter":"H"
			}
			,{
			"id":52
			,"canbedisplayed":true
			,"description":"INNOCENTI"
			,"fulldescription":"INNOCENTI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"INNOC"
			,"firstlatter":"I"
			}
			,{
			"id":54
			,"canbedisplayed":true
			,"description":"ISUZU"
			,"fulldescription":"ISUZU"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ISUZU"
			,"firstlatter":"I"
			}
			,{
			"id":55
			,"canbedisplayed":true
			,"description":"IVECO"
			,"fulldescription":"IVECO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"IVECO"
			,"firstlatter":"I"
			}
			,{
			"id":1507
			,"canbedisplayed":true
			,"description":"INDIGO"
			,"fulldescription":"INDIGO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"INDIGO"
			,"firstlatter":"I"
			}
			,{
			"id":4683
			,"canbedisplayed":true
			,"description":"IZH"
			,"fulldescription":"IZH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"IZH"
			,"firstlatter":"I"
			}
			,{
			"id":1509
			,"canbedisplayed":true
			,"description":"ISDERA"
			,"fulldescription":"ISDERA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ISDER"
			,"firstlatter":"I"
			}
			,{
			"id":1510
			,"canbedisplayed":true
			,"description":"ISH"
			,"fulldescription":"ISH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ISH"
			,"firstlatter":"I"
			}
			,{
			"id":1526
			,"canbedisplayed":true
			,"description":"INFINITI"
			,"fulldescription":"INFINITI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"INFIN"
			,"firstlatter":"I"
			}
			,{
			"id":1508
			,"canbedisplayed":true
			,"description":"IRMSCHER"
			,"fulldescription":"IRMSCHER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"IRMSCHER"
			,"firstlatter":"I"
			}
			,{
			"id":56
			,"canbedisplayed":true
			,"description":"JAGUAR"
			,"fulldescription":"JAGUAR"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"JAGUA"
			,"firstlatter":"J"
			}
			,{
			"id":882
			,"canbedisplayed":true
			,"description":"JEEP"
			,"fulldescription":"JEEP"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"JEEP"
			,"firstlatter":"J"
			}
			,{
			"id":3040
			,"canbedisplayed":true
			,"description":"JMC"
			,"fulldescription":"JMC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"JMC"
			,"firstlatter":"J"
			}
			,{
			"id":2873
			,"canbedisplayed":true
			,"description":"JAC"
			,"fulldescription":"JAC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"JAC"
			,"firstlatter":"J"
			}
			,{
			"id":1511
			,"canbedisplayed":true
			,"description":"JENSEN"
			,"fulldescription":"JENSEN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"JENSE"
			,"firstlatter":"J"
			}
			,{
			"id":184
			,"canbedisplayed":true
			,"description":"KIA"
			,"fulldescription":"KIA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"KIA"
			,"firstlatter":"K"
			}
			,{
			"id":3805
			,"canbedisplayed":true
			,"description":"KING LONG"
			,"fulldescription":"KING LONG"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"KING LONG"
			,"firstlatter":"K"
			}
			,{
			"id":2760
			,"canbedisplayed":true
			,"description":"KTM"
			,"fulldescription":"KTM"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"KTM"
			,"firstlatter":"K"
			}
			,{
			"id":63
			,"canbedisplayed":true
			,"description":"LADA"
			,"fulldescription":"LADA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LADA"
			,"firstlatter":"L"
			}
			,{
			"id":64
			,"canbedisplayed":true
			,"description":"LANCIA"
			,"fulldescription":"LANCIA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LANCIA"
			,"firstlatter":"L"
			}
			,{
			"id":701
			,"canbedisplayed":true
			,"description":"LAMBORGHINI"
			,"fulldescription":"LAMBORGHINI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LAMBO"
			,"firstlatter":"L"
			}
			,{
			"id":802
			,"canbedisplayed":true
			,"description":"LOTUS"
			,"fulldescription":"LOTUS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LOTUS"
			,"firstlatter":"L"
			}
			,{
			"id":842
			,"canbedisplayed":true
			,"description":"LEXUS"
			,"fulldescription":"LEXUS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LEXUS"
			,"firstlatter":"L"
			}
			,{
			"id":1200
			,"canbedisplayed":true
			,"description":"LINCOLN"
			,"fulldescription":"LINCOLN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LINCO"
			,"firstlatter":"L"
			}
			,{
			"id":3742
			,"canbedisplayed":true
			,"description":"LUXGEN"
			,"fulldescription":"LUXGEN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LUXGEN"
			,"firstlatter":"L"
			}
			,{
			"id":1513
			,"canbedisplayed":true
			,"description":"LIGIER"
			,"fulldescription":"LIGIER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LIGIER"
			,"firstlatter":"L"
			}
			,{
			"id":1820
			,"canbedisplayed":true
			,"description":"LAND ROVER"
			,"fulldescription":"LAND ROVER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LANDROVER"
			,"firstlatter":"L"
			}
			,{
			"id":2589
			,"canbedisplayed":true
			,"description":"LANDWIND (JMC)"
			,"fulldescription":"LANDWIND (JMC)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LANDWIND"
			,"firstlatter":"L"
			}
			,{
			"id":3047
			,"canbedisplayed":true
			,"description":"LTI"
			,"fulldescription":"LTI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LTI"
			,"firstlatter":"L"
			}
			,{
			"id":3086
			,"canbedisplayed":true
			,"description":"LIFAN"
			,"fulldescription":"LIFAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LIFAN"
			,"firstlatter":"L"
			}
			,{
			"id":1380
			,"canbedisplayed":true
			,"description":"LDV"
			,"fulldescription":"LDV"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"LDV"
			,"firstlatter":"L"
			}
			,{
			"id":69
			,"canbedisplayed":true
			,"description":"MAN"
			,"fulldescription":"MAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MAN"
			,"firstlatter":"M"
			}
			,{
			"id":2904
			,"canbedisplayed":true
			,"description":"MITSUOKA"
			,"fulldescription":"MITSUOKA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MITSUOKA"
			,"firstlatter":"M"
			}
			,{
			"id":74
			,"canbedisplayed":true
			,"description":"MERCEDES-BENZ"
			,"fulldescription":"MERCEDES-BENZ"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MERCE"
			,"firstlatter":"M"
			}
			,{
			"id":75
			,"canbedisplayed":true
			,"description":"MG"
			,"fulldescription":"MG"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MG"
			,"firstlatter":"M"
			}
			,{
			"id":77
			,"canbedisplayed":true
			,"description":"MITSUBISHI"
			,"fulldescription":"MITSUBISHI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MITSUBISHI"
			,"firstlatter":"M"
			}
			,{
			"id":78
			,"canbedisplayed":true
			,"description":"MORRIS"
			,"fulldescription":"MORRIS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MORRI"
			,"firstlatter":"M"
			}
			,{
			"id":771
			,"canbedisplayed":true
			,"description":"MASERATI"
			,"fulldescription":"MASERATI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MASER"
			,"firstlatter":"M"
			}
			,{
			"id":803
			,"canbedisplayed":true
			,"description":"MORGAN"
			,"fulldescription":"MORGAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MORGA"
			,"firstlatter":"M"
			}
			,{
			"id":813
			,"canbedisplayed":true
			,"description":"MOSKVICH"
			,"fulldescription":"MOSKVICH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MOSKV"
			,"firstlatter":"M"
			}
			,{
			"id":845
			,"canbedisplayed":true
			,"description":"MEGA"
			,"fulldescription":"MEGA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MEGA"
			,"firstlatter":"M"
			}
			,{
			"id":1280
			,"canbedisplayed":true
			,"description":"MAHINDRA"
			,"fulldescription":"MAHINDRA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MAHINDRA"
			,"firstlatter":"M"
			}
			,{
			"id":1516
			,"canbedisplayed":true
			,"description":"MARCOS"
			,"fulldescription":"MARCOS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MARCOS"
			,"firstlatter":"M"
			}
			,{
			"id":1518
			,"canbedisplayed":true
			,"description":"MCLAREN"
			,"fulldescription":"MCLAREN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MCLAREN"
			,"firstlatter":"M"
			}
			,{
			"id":1520
			,"canbedisplayed":true
			,"description":"METROCAB"
			,"fulldescription":"METROCAB"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"METROCAB"
			,"firstlatter":"M"
			}
			,{
			"id":1521
			,"canbedisplayed":true
			,"description":"MIDDLEBRIDGE"
			,"fulldescription":"MIDDLEBRIDGE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MIDDL"
			,"firstlatter":"M"
			}
			,{
			"id":1522
			,"canbedisplayed":true
			,"description":"MINELLI"
			,"fulldescription":"MINELLI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MINELLI"
			,"firstlatter":"M"
			}
			,{
			"id":1523
			,"canbedisplayed":true
			,"description":"MINI"
			,"fulldescription":"MINI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MINI"
			,"firstlatter":"M"
			}
			,{
			"id":2164
			,"canbedisplayed":true
			,"description":"MAYBACH"
			,"fulldescription":"MAYBACH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MAYB"
			,"firstlatter":"M"
			}
			,{
			"id":72
			,"canbedisplayed":true
			,"description":"MAZDA"
			,"fulldescription":"MAZDA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"MAZDA"
			,"firstlatter":"M"
			}
			,{
			"id":80
			,"canbedisplayed":true
			,"description":"NISSAN"
			,"fulldescription":"NISSAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"NISSA"
			,"firstlatter":"N"
			}
			,{
			"id":3141
			,"canbedisplayed":true
			,"description":"NISSAN (DONGFENG)"
			,"fulldescription":"NISSAN (DONGFENG)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"NISSAN DF"
			,"firstlatter":"N"
			}
			,{
			"id":81
			,"canbedisplayed":true
			,"description":"NSU"
			,"fulldescription":"NSU"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"NSU"
			,"firstlatter":"N"
			}
			,{
			"id":84
			,"canbedisplayed":true
			,"description":"OPEL"
			,"fulldescription":"OPEL"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"OPEL"
			,"firstlatter":"O"
			}
			,{
			"id":1529
			,"canbedisplayed":true
			,"description":"OSCA"
			,"fulldescription":"OSCA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"OSCA"
			,"firstlatter":"O"
			}
			,{
			"id":1527
			,"canbedisplayed":true
			,"description":"OLTCIT"
			,"fulldescription":"OLTCIT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"OLTCI"
			,"firstlatter":"O"
			}
			,{
			"id":1141
			,"canbedisplayed":true
			,"description":"OLDSMOBILE"
			,"fulldescription":"OLDSMOBILE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"OLDS"
			,"firstlatter":"O"
			}
			,{
			"id":88
			,"canbedisplayed":true
			,"description":"PEUGEOT"
			,"fulldescription":"PEUGEOT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PEUGE"
			,"firstlatter":"P"
			}
			,{
			"id":92
			,"canbedisplayed":true
			,"description":"PORSCHE"
			,"fulldescription":"PORSCHE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PORSC"
			,"firstlatter":"P"
			}
			,{
			"id":181
			,"canbedisplayed":true
			,"description":"PIAGGIO"
			,"fulldescription":"PIAGGIO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PIAGGIO"
			,"firstlatter":"P"
			}
			,{
			"id":774
			,"canbedisplayed":true
			,"description":"PONTIAC"
			,"fulldescription":"PONTIAC"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PONTI"
			,"firstlatter":"P"
			}
			,{
			"id":778
			,"canbedisplayed":true
			,"description":"PROTON"
			,"fulldescription":"PROTON"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PROTO"
			,"firstlatter":"P"
			}
			,{
			"id":3046
			,"canbedisplayed":true
			,"description":"PININFARINA"
			,"fulldescription":"PININFARINA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PININFARIN"
			,"firstlatter":"P"
			}
			,{
			"id":851
			,"canbedisplayed":true
			,"description":"PREMIER"
			,"fulldescription":"PREMIER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PREMI"
			,"firstlatter":"P"
			}
			,{
			"id":1530
			,"canbedisplayed":true
			,"description":"PANOZ"
			,"fulldescription":"PANOZ"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PANOZ"
			,"firstlatter":"P"
			}
			,{
			"id":1531
			,"canbedisplayed":true
			,"description":"PANTHER"
			,"fulldescription":"PANTHER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PANTH"
			,"firstlatter":"P"
			}
			,{
			"id":1532
			,"canbedisplayed":true
			,"description":"PAYKAN"
			,"fulldescription":"PAYKAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PAYKA"
			,"firstlatter":"P"
			}
			,{
			"id":1580
			,"canbedisplayed":true
			,"description":"PUCH"
			,"fulldescription":"PUCH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PUCH"
			,"firstlatter":"P"
			}
			,{
			"id":850
			,"canbedisplayed":true
			,"description":"PLYMOUTH"
			,"fulldescription":"PLYMOUTH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"PLYMOUTH"
			,"firstlatter":"P"
			}
			,{
			"id":93
			,"canbedisplayed":true
			,"description":"RENAULT"
			,"fulldescription":"RENAULT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RENAU"
			,"firstlatter":"R"
			}
			,{
			"id":95
			,"canbedisplayed":true
			,"description":"ROVER"
			,"fulldescription":"ROVER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ROVER"
			,"firstlatter":"R"
			}
			,{
			"id":694
			,"canbedisplayed":true
			,"description":"RENAULT TRUCKS"
			,"fulldescription":"RENAULT TRUCKS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RENAULT"
			,"firstlatter":"R"
			}
			,{
			"id":705
			,"canbedisplayed":true
			,"description":"ROLLS-ROYCE"
			,"fulldescription":"ROLLS-ROYCE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ROLLS"
			,"firstlatter":"R"
			}
			,{
			"id":4660
			,"canbedisplayed":true
			,"description":"RAVON"
			,"fulldescription":"RAVON"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RAVON"
			,"firstlatter":"R"
			}
			,{
			"id":1534
			,"canbedisplayed":true
			,"description":"RANGER"
			,"fulldescription":"RANGER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RANGER"
			,"firstlatter":"R"
			}
			,{
			"id":1536
			,"canbedisplayed":true
			,"description":"RAYTON FISSORE"
			,"fulldescription":"RAYTON FISSORE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RAYTO"
			,"firstlatter":"R"
			}
			,{
			"id":1539
			,"canbedisplayed":true
			,"description":"RILEY"
			,"fulldescription":"RILEY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RILEY"
			,"firstlatter":"R"
			}
			,{
			"id":4152
			,"canbedisplayed":true
			,"description":"RUF"
			,"fulldescription":"RUF"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RUF"
			,"firstlatter":"R"
			}
			,{
			"id":773
			,"canbedisplayed":true
			,"description":"RELIANT"
			,"fulldescription":"RELIANT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"RELIANT"
			,"firstlatter":"R"
			}
			,{
			"id":99
			,"canbedisplayed":true
			,"description":"SAAB"
			,"fulldescription":"SAAB"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SAAB"
			,"firstlatter":"S"
			}
			,{
			"id":4260
			,"canbedisplayed":true
			,"description":"SAMSUNG"
			,"fulldescription":"SAMSUNG"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SAMSUNG"
			,"firstlatter":"S"
			}
			,{
			"id":106
			,"canbedisplayed":true
			,"description":"SKODA"
			,"fulldescription":"SKODA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SKODA"
			,"firstlatter":"S"
			}
			,{
			"id":107
			,"canbedisplayed":true
			,"description":"SUBARU"
			,"fulldescription":"SUBARU"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SUBAR"
			,"firstlatter":"S"
			}
			,{
			"id":109
			,"canbedisplayed":true
			,"description":"SUZUKI"
			,"fulldescription":"SUZUKI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SUZUK"
			,"firstlatter":"S"
			}
			,{
			"id":171
			,"canbedisplayed":true
			,"description":"SANTANA"
			,"fulldescription":"SANTANA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SANTANA"
			,"firstlatter":"S"
			}
			,{
			"id":175
			,"canbedisplayed":true
			,"description":"SSANGYONG"
			,"fulldescription":"SSANGYONG"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SSANG"
			,"firstlatter":"S"
			}
			,{
			"id":176
			,"canbedisplayed":true
			,"description":"STEYR"
			,"fulldescription":"STEYR"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"STEYR"
			,"firstlatter":"S"
			}
			,{
			"id":1138
			,"canbedisplayed":true
			,"description":"SMART"
			,"fulldescription":"SMART"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SMART"
			,"firstlatter":"S"
			}
			,{
			"id":1547
			,"canbedisplayed":true
			,"description":"SHELBY"
			,"fulldescription":"SHELBY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SHELB"
			,"firstlatter":"S"
			}
			,{
			"id":1548
			,"canbedisplayed":true
			,"description":"SIPANI"
			,"fulldescription":"SIPANI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SIPAN"
			,"firstlatter":"S"
			}
			,{
			"id":1549
			,"canbedisplayed":true
			,"description":"SPECTRE"
			,"fulldescription":"SPECTRE"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SPECTRE"
			,"firstlatter":"S"
			}
			,{
			"id":1550
			,"canbedisplayed":true
			,"description":"STANDARD"
			,"fulldescription":"STANDARD"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"STAND"
			,"firstlatter":"S"
			}
			,{
			"id":2755
			,"canbedisplayed":true
			,"description":"SPYKER"
			,"fulldescription":"SPYKER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SPYKER"
			,"firstlatter":"S"
			}
			,{
			"id":3156
			,"canbedisplayed":true
			,"description":"SHUANGHUAN"
			,"fulldescription":"SHUANGHUAN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SHUANGHUAN"
			,"firstlatter":"S"
			}
			,{
			"id":4015
			,"canbedisplayed":true
			,"description":"STREETSCOOTER"
			,"fulldescription":"STREETSCOOTER"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"STREETSCOO"
			,"firstlatter":"S"
			}
			,{
			"id":104
			,"canbedisplayed":true
			,"description":"SEAT"
			,"fulldescription":"SEAT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"SEAT"
			,"firstlatter":"S"
			}
			,{
			"id":110
			,"canbedisplayed":true
			,"description":"TALBOT"
			,"fulldescription":"TALBOT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TALBO"
			,"firstlatter":"T"
			}
			,{
			"id":111
			,"canbedisplayed":true
			,"description":"TOYOTA"
			,"fulldescription":"TOYOTA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TOYOT"
			,"firstlatter":"T"
			}
			,{
			"id":112
			,"canbedisplayed":true
			,"description":"TRIUMPH"
			,"fulldescription":"TRIUMPH"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TRIUM"
			,"firstlatter":"T"
			}
			,{
			"id":178
			,"canbedisplayed":true
			,"description":"TATA"
			,"fulldescription":"TATA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TATA"
			,"firstlatter":"T"
			}
			,{
			"id":187
			,"canbedisplayed":true
			,"description":"TRABANT"
			,"fulldescription":"TRABANT"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TRABA"
			,"firstlatter":"T"
			}
			,{
			"id":861
			,"canbedisplayed":true
			,"description":"TVR"
			,"fulldescription":"TVR"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TVR"
			,"firstlatter":"T"
			}
			,{
			"id":4292
			,"canbedisplayed":true
			,"description":"TAGAZ"
			,"fulldescription":"TAGAZ"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TAGAZ"
			,"firstlatter":"T"
			}
			,{
			"id":3130
			,"canbedisplayed":true
			,"description":"TOYOTA (GAC)"
			,"fulldescription":"TOYOTA (GAC)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TOYOTA GAC"
			,"firstlatter":"T"
			}
			,{
			"id":3137
			,"canbedisplayed":true
			,"description":"TOYOTA (FAW)"
			,"fulldescription":"TOYOTA (FAW)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TOYOTA FAW"
			,"firstlatter":"T"
			}
			,{
			"id":3328
			,"canbedisplayed":true
			,"description":"TESLA"
			,"fulldescription":"TESLA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TESLA M."
			,"firstlatter":"T"
			}
			,{
			"id":3443
			,"canbedisplayed":true
			,"description":"TAZZARI"
			,"fulldescription":"TAZZARI"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TAZZARI"
			,"firstlatter":"T"
			}
			,{
			"id":3514
			,"canbedisplayed":true
			,"description":"THINK"
			,"fulldescription":"THINK"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"THINK"
			,"firstlatter":"T"
			}
			,{
			"id":1551
			,"canbedisplayed":true
			,"description":"TOFAS"
			,"fulldescription":"TOFAS"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"TOFAS"
			,"firstlatter":"T"
			}
			,{
			"id":1554
			,"canbedisplayed":true
			,"description":"UMM"
			,"fulldescription":"UMM"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"UMM"
			,"firstlatter":"U"
			}
			,{
			"id":1553
			,"canbedisplayed":true
			,"description":"UAZ"
			,"fulldescription":"UAZ"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"UAZ"
			,"firstlatter":"U"
			}
			,{
			"id":117
			,"canbedisplayed":true
			,"description":"VAUXHALL"
			,"fulldescription":"VAUXHALL"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"VAUXH"
			,"firstlatter":"V"
			}
			,{
			"id":1555
			,"canbedisplayed":true
			,"description":"VECTOR"
			,"fulldescription":"VECTOR"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"VECTO"
			,"firstlatter":"V"
			}
			,{
			"id":121
			,"canbedisplayed":true
			,"description":"VW"
			,"fulldescription":"VW"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"VW"
			,"firstlatter":"V"
			}
			,{
			"id":120
			,"canbedisplayed":true
			,"description":"VOLVO"
			,"fulldescription":"VOLVO"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":true
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"VOLVO"
			,"firstlatter":"V"
			}
			,{
			"id":186
			,"canbedisplayed":true
			,"description":"WARTBURG"
			,"fulldescription":"WARTBURG"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"WARTB"
			,"firstlatter":"W"
			}
			,{
			"id":1558
			,"canbedisplayed":true
			,"description":"WIESMANN"
			,"fulldescription":"WIESMANN"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"WIESMANN"
			,"firstlatter":"W"
			}
			,{
			"id":1541
			,"canbedisplayed":true
			,"description":"WOLSELEY"
			,"fulldescription":"WOLSELEY"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"WOLSE"
			,"firstlatter":"W"
			}
			,{
			"id":907
			,"canbedisplayed":true
			,"description":"WESTFIELD"
			,"fulldescription":"WESTFIELD"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"WESTFIELD"
			,"firstlatter":"W"
			}
			,{
			"id":1559
			,"canbedisplayed":true
			,"description":"YULON"
			,"fulldescription":"YULON"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"YULON"
			,"firstlatter":"Y"
			}
			,{
			"id":124
			,"canbedisplayed":true
			,"description":"ZASTAVA"
			,"fulldescription":"ZASTAVA"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ZASTA"
			,"firstlatter":"Z"
			}
			,{
			"id":2911
			,"canbedisplayed":true
			,"description":"ZHONGXING (ZTE)"
			,"fulldescription":"ZHONGXING (ZTE)"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ZHONGXING"
			,"firstlatter":"Z"
			}
			,{
			"id":1139
			,"canbedisplayed":true
			,"description":"ZAZ"
			,"fulldescription":"ZAZ"
			,"haslink":true
			,"isaxle":false
			,"iscommercialvehicle":false
			,"isengine":false
			,"ismotorbike":false
			,"ispassengercar":true
			,"istransporter":false
			,"isvgl":false
			,"matchcode":"ZAZ"
			,"firstlatter":"Z"
			}
			]
		}*/
			

	})


}, false);